name       : gstreamer-1.0
version    : 1.14.4
release    : 24
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.14.4.tar.xz : f94f6696c5f05a3b3a9183e39c5f5c0b779f75a04c0efa497e7920afa985ffc7
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins
    for things like video encoding and decoding, audio encoding and decoding, audio and video filters,
    audio visualisation, web streaming and anything else that streams in real-time or otherwise.
    This package only provides base functionality and libraries.
    You may need at least gst-plugins-base and one of Good, Bad, Ugly or Libav plugins.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk-doc)
setup      : |
    %configure --disable-static --with-package-name="GStreamer ${version} Solus" \
        --with-package-origin="https://getsol.us" \
        --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
