name       : gstreamer-1.0
version    : 1.18.5
release    : 35
source     :
    - https://gitlab.freedesktop.org/gstreamer/gstreamer/-/archive/1.18.5/gstreamer-1.18.5.tar.gz : cd3bf14c14117acc5cb49aaa661db0d1934fb568896a097790ea84e8d0a6cf14
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
homepage   : https://gitlab.freedesktop.org/gstreamer/gstreamer
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins for things like video encoding and decoding, audio encoding and decoding, audio and video filters, audio visualisation, web streaming and anything else that streams in real-time or otherwise. This package only provides base functionality and libraries. You may need at least gst-plugins-base and one of Good, Bad, Ugly or Libav plugins.
emul32     : yes
builddeps  :
    - pkgconfig32(glib-2.0)
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - 32bit :
        - /usr/share/gdb/auto-load/usr/lib32/
setup      : |
    if [[ -n "${EMUL32BUILD}" ]]; then
        CONFIGURE_OPTIONS="-Dintrospection=disabled"
    fi

    %meson_configure -Dpackage-name="GStreamer ${version} Solus" \
        -Dpackage-origin="https://getsol.us" \
        -Dgobject-cast-checks=disabled \
        -Dglib-asserts=disabled \
        -Dglib-checks=disabled \
        $CONFIGURE_OPTIONS
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
