name       : gstreamer-1.0
version    : 1.16.0
release    : 25
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.16.0.tar.xz : 0e8e2f7118be437cba879353970cf83c2acced825ecb9275ba05d9186ef07c00
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins
    for things like video encoding and decoding, audio encoding and decoding, audio and video filters,
    audio visualisation, web streaming and anything else that streams in real-time or otherwise.
    This package only provides base functionality and libraries.
    You may need at least gst-plugins-base and one of Good, Bad, Ugly or Libav plugins.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk-doc)
setup      : |
    %meson_configure -D package-name="GStreamer ${version} Solus" \
        -D package-origin="https://getsol.us" \
        -D gobject-cast-checks=disabled \
        -D glib-asserts=disabled \
        -D glib-checks=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
