name       : gstreamer-1.0
version    : 1.18.1
release    : 30
source     :
    - https://gitlab.freedesktop.org/gstreamer/gstreamer/-/archive/1.18.1/gstreamer-1.18.1.tar.gz : a0c11a823b1ba88b8450286be1794b9dd9f27f005a2bdf83eb1a5e14efcff06b
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
homepage   : https://gitlab.freedesktop.org/gstreamer/gstreamer
summary    : Streaming media framework
description: |
    GStreamer is a streaming media framework that enables applications to share a common set of plugins for things like video encoding and decoding, audio encoding and decoding, audio and video filters, audio visualisation, web streaming and anything else that streams in real-time or otherwise. This package only provides base functionality and libraries. You may need at least gst-plugins-base and one of Good, Bad, Ugly or Libav plugins.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %meson_configure -D package-name="GStreamer ${version} Solus" \
        -D package-origin="https://getsol.us" \
        -D gobject-cast-checks=disabled \
        -D glib-asserts=disabled \
        -D glib-checks=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
